Name:           ros-kinetic-roch-follower
Version:        2.0.12
Release:        0%{?dist}
Summary:        ROS roch_follower package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/roch_follower
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-depth-image-proc
Requires:       ros-kinetic-dynamic-reconfigure
Requires:       ros-kinetic-nodelet
Requires:       ros-kinetic-roch-bringup
Requires:       ros-kinetic-roch-msgs
Requires:       ros-kinetic-roch-teleop
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-topic-tools
Requires:       ros-kinetic-visualization-msgs
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-depth-image-proc
BuildRequires:  ros-kinetic-dynamic-reconfigure
BuildRequires:  ros-kinetic-nodelet
BuildRequires:  ros-kinetic-roch-msgs
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-visualization-msgs

%description
Follower for the roch. Follows humans and robots around by following the
centroid of a box points in front of the roch.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon Sep 18 2017 Carl <wzhang@softrobetch.com> - 2.0.12-0
- Autogenerated by Bloom

* Fri Mar 24 2017 Carl <wzhang@softrobetch.com> - 2.0.11-0
- Autogenerated by Bloom

