Name:           ros-indigo-roch-bringup
Version:        1.0.7
Release:        0%{?dist}
Summary:        ROS roch_bringup package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/roch_bringup
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-depthimage-to-laserscan
Requires:       ros-indigo-freenect-launch
Requires:       ros-indigo-imu-filter-madgwick
Requires:       ros-indigo-imu-transformer
Requires:       ros-indigo-microstrain-3dmgx2-imu
Requires:       ros-indigo-nmea-comms
Requires:       ros-indigo-nmea-navsat-driver
Requires:       ros-indigo-openni2-launch
Requires:       ros-indigo-realsense-camera
Requires:       ros-indigo-robot-localization
Requires:       ros-indigo-robot-upstart
Requires:       ros-indigo-roch-base
Requires:       ros-indigo-roch-control
Requires:       ros-indigo-roch-description
Requires:       ros-indigo-roch-safety-controller
Requires:       ros-indigo-roch-sensorpc
Requires:       ros-indigo-rospy
Requires:       ros-indigo-rplidar-ros
Requires:       ros-indigo-tf
Requires:       ros-indigo-tf2-ros
Requires:       ros-indigo-ur-driver
Requires:       scipy
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-roslaunch
BuildRequires:  ros-indigo-rospy

%description
SawYer roch installation and integration package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Jan 22 2017 Carl <wzhang@softrobtech.com> - 1.0.7-0
- Autogenerated by Bloom

